routes:
  /signin/: members/signin
  /signup/: members/signup
  /login/: members/signin
  /account/: members/account
  /:
    data: page.home
    template: home

collections:
  /blog/:
    permalink: /blog/{slug}/
    template:
      - index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
